# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitops-zombies" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_darwin_amd64.tar.gz"
      sha256 "a0c43086990d537bd28e2c368b4f599d487b34fd3c2ce64279b158d8c19f05a1"
    end
    on_arm do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_darwin_arm64.tar.gz"
      sha256 "bb3bcbc06058b06cc9d35b10b340a9f4a02c76eadf95ceb3b79ae907d23fbe0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_linux_amd64.tar.gz"
      sha256 "4a67851b124a1eb5ba7024041161078b83d962d512159698965b933ab18825b6"
    end
    on_arm do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_linux_arm64.tar.gz"
      sha256 "74dd676a856666f98af69d54d74ab418c65e10c4440113c91aa42ca7cccb7828"
    end
  end

  name "gitops-zombies"
  desc "Identify kubernetes resources which are not managed by GitOps"
  homepage "https://github.com/raffis/gitops-zombies"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitops-zombies"

  # No zap stanza required

end
