# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitops-zombies" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_darwin_amd64.tar.gz"
      sha256 "0722c5f05112e7ace2ad4bc5e9752341bad23b183902cd29e8f57076b0c81189"
    end
    on_arm do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_darwin_arm64.tar.gz"
      sha256 "b11ec5886ab98f0dcf02c12cedb2c335068b7bbd02a25b36ae797441f50f8dd5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_linux_amd64.tar.gz"
      sha256 "d182db9d6348a57c0bb55d9c0d056e128fdfc3142598107a53f8033ec426bbec"
    end
    on_arm do
      url "https://github.com/raffis/gitops-zombies/releases/download/v#{version}/gitops-zombies_#{version}_linux_arm64.tar.gz"
      sha256 "f879bbd25e66f74996e1241d21fc96e5c8b285da1c7c6d9a9b8de9e47d08a098"
    end
  end

  name "gitops-zombies"
  desc "Identify kubernetes resources which are not managed by GitOps"
  homepage "https://github.com/raffis/gitops-zombies"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitops-zombies"

  # No zap stanza required

end
