# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitopsZombies < Formula
  desc ""
  homepage ""
  version "0.0.2"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/gitops-zombies/releases/download/v0.0.2/gitops-zombies_0.0.2_linux_arm64.tar.gz"
      sha256 "b777600540c92a4bab10f0e8b2a9351ae89e5d0af1c95f8983b9a597943fdf00"

      def install
        bin.install "gitops-zombies"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/gitops-zombies/releases/download/v0.0.2/gitops-zombies_0.0.2_linux_amd64.tar.gz"
      sha256 "510d314bdef115ada8d1c3cde5ca07d740ed3f782276be002c0451bde8472ff8"

      def install
        bin.install "gitops-zombies"
      end
    end
  end

  test do
    system "#{bin}/kjournal help"
  end
end
