# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitopsZombies < Formula
  desc "Identify kubernetes resources which are not managed by GitOps"
  homepage "https://github.com/raffis/gitops-zombies"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/raffis/gitops-zombies/archive/refs/tags/v0.1.0.tar.gz"
      sha256 "29e1e7d71ec146a5ac1b7a8568bdeed4b78321c36776f26db85551098a28fc4c"

      def install
        bin.install "gitops-zombies"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/gitops-zombies/releases/download/v0.0.9/gitops-zombies_0.0.9_darwin_amd64.tar.gz"
      sha256 "c32e2fce82f5aede464b04b5d23f5d2bf45d0fd3156a1430c5f0d7fe25ba475a"

      def install
        bin.install "gitops-zombies"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/gitops-zombies/releases/download/v0.0.9/gitops-zombies_0.0.9_linux_arm64.tar.gz"
      sha256 "802ea6c98e213bfed8f0dca1adfa4cf14710377a573375ce01f6b767eec3621b"

      def install
        bin.install "gitops-zombies"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/gitops-zombies/releases/download/v0.0.9/gitops-zombies_0.0.9_linux_amd64.tar.gz"
      sha256 "eb79eb025955e188262ddfbf1ff9a971c452c823359e77e867717ee4bd9bc2ff"

      def install
        bin.install "gitops-zombies"
      end
    end
  end

  test do
    system "#{bin}/gitops-zombies -h"
  end
end
