name: pr-label

on:
  pull_request:

permissions: {}

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    if: '!github.event.pull_request.head.repo.fork'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: size-label
        uses: "pascalgn/size-label-action@6ec5bd0f81af1bd8d691180fbf04453b2c4b1642"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

