name: pr-label
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@49850f3557d4b77f0b2e759829defd77ccc07c54"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
