name: pr-stale
on:
  schedule:
    - cron: '30 1 * * *'

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
    - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
      with:
        days-before-close: '120'
        stale-pr-label: stale
        repo-token: ${{ github.token }}
